### ISSUE TITLE
Ignore/exclude directories

### ISSUE THREAD

**Issue by mykt0ngc0** [jkphl/gulp-concat-flatten#16]
Hi @jkphl, thanks for making this plugin.
I'd like to know if there is a way to ignore directories with this?

**Comment by jkphl** [comment]
Sorry for the late reply, @mykt0ngc0!

Well, I'm not totally sure if it's the right syntax (not using Gulp a lot these days), but you should be able to exclude files or directories by using something like this (mind the exclamation mark "!"; standard functionality, not specific to this package):

```js
gulp.src(['path/**/*.txt', '!path/to/exclude/**/*.txt']).
  .pipe(sort(…
```

Hope this helps!

**Comment by mykt0ngc0** [comment]
Thanks @jkphl!
