### ISSUE TITLE
It is including base structure inside destination

### ISSUE THREAD

**Issue by nitin2953** [jkphl/gulp-concat-flatten#19]
```js
function js() {
	return src("./src/assets/js/**/*.js")
		.pipe(concatFlatten("./src/assets/js", "js"))
		.pipe(dest("./dist/assets/js/"));
}
```
I want this
```
src
`-- assets
    `-- js
        |-- main
        |   |-- menu.js
        |   `-- search.js
        |-- third
        |   |-- photoswipe.js
        |   `-- temporal.js
        |-- test.js
        `-- tmp.js
```
```
dist
`-- assets
    `-- js
        |-- main.js
        |-- third.js
        |-- test.js
        `-- tmp.js
```

BUT it is doing this
```
dist
`-- assets
    `-- js
        `-- src
            `-- assets
                `-- js
                    |-- main.js
                    |-- third.js
                    |-- test.js
                    `-- tmp.js
```

**Comment by jkphl** [comment]
I'm not using the package too much these days and I don't have the capacity to dig into this right now, unfortunately. But off the top of my head: Did you try using the `cwd` or `base` option for `gulp.src()`, like e. g. `gulp.src("./src/assets/js/**/*.js", {cwd: "./src/assets/js"})`? (It might also be `gulp.src("**/*.js", {cwd: "./src/assets/js"})` in that case, dunno …)

**Comment by nitin2953** [comment]
😍 Great the last one is working
```js
function js() {
	return src("**/*.js", {cwd: "./src/assets/js"})
		.pipe(concatFlatten("./src/assets/js", "js"))
		.pipe(dest("dist/assets/js/"));
}
```
But if I include multiple src location (outside of cwd) then this will not work
```js
src(["**/*.js", "./local/**/*.js"], {cwd: "./src/assets/js"})
      ^^^^^^^
./src/assets/js/**/*.js
```

**Comment by jkphl** [comment]
That's true — but it's also not how the package is intended to work. It's meant to collapse directory contents by directory name, and with the `cwd` option (current working directory) you can determine **one single base directory** for the name collapsing process. The `src` arguments are interpreted **relative to the working directory** —  so if you specify a `src` path that doesn't exist inside the `cwd` how should that work? In that case you'll have to run multiple processes with reasonable configs each.
